### ISSUE TITLE
Calling a method that does not exists doesn't throw explicit exception

### ISSUE THREAD

**Issue by jupaol** [davidebbo/ReflectionMagic#5] opened 2015-03-04 22:50 UTC
Hi

I was using the code directly in my application and I just migrated to use the Nuget, all my tests seem to pass except this one: (it was green before updating to use the Nuget)

```
        [TestMethod]
        public void it_should_throw_an_exception_if_the_method_does_not_exist()
        {
            var originalObject = new SimpleObject();
            var sut = originalObject.AsDynamic();
            Action a = () => sut.DoesNotExistMethod("dede");

            a.ShouldThrow<MissingMethodException>().WithMessage("*DoesNotExistMethod*");
        }
```

Instead it throws:

```
Result Message: 
Expected a <System.MissingMethodException> to be thrown, but found a <System.ApplicationException>: System.ApplicationException with message "Error in the application."
     at ReflectionMagic.PrivateReflectionDynamicObjectBase.InvokeMethodOnType(Type type, Object target, String name, Object[] args, IList`1 typeArgs)
     at ReflectionMagic.PrivateReflectionDynamicObjectBase.InvokeMethodOnType(Type type, Object target, String name, Object[] args, IList`1 typeArgs)
     at ReflectionMagic.PrivateReflectionDynamicObjectBase.InvokeMethodOnType(Type type, Object target, String name, Object[] args, IList`1 typeArgs)
     at ReflectionMagic.PrivateReflectionDynamicObjectBase.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
     at CallSite.Target(Closure , CallSite , Object , String )
     at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
```

It's not high severity, I just wanted to let you know

Good job, I love this tool

**Comment by davidebbo** [comment] 2015-03-04 22:58
I'm not sure I understand what you were using before moving to the NuGet. Some older version of ReflectionMagic?

Anyway, if you find a fix, feel free to send a PR :)

**Comment by jvandertil** [comment] 2016-11-23 12:41
The issue is here: [PrivateReflectionDynamicObjectBase.cs#L179](https://github.com/davidebbo/ReflectionMagic/blob/master/src/ReflectionMagic/PrivateReflectionDynamicObjectBase.cs#L179). It seems that throwing a MissingMethodException at this point is valid.

I think I'll move it down though, like this:

```cs
...
if(method == null) 
{
  if(type.GetTypeInfo().BaseType == null) 
  {
     throw MissingMethodException(...);
  }
}
....
```
and convert the first `type == null` check to throw an ArgumentNullException instead.

**Closed** 2016-12-27 17:33 UTC
